# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-api-new"
client_id = "fd3916b844cbc935b7358a3f28458ff6"
application_url = "https://facts-soil-courtesy-grain.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://facts-soil-courtesy-grain.trycloudflare.com/auth/callback",
  "https://facts-soil-courtesy-grain.trycloudflare.com/auth/shopify/callback",
  "https://facts-soil-courtesy-grain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sealion4.myshopify.com"
