# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reemind-me"
client_id = "6c2fc68fb36229fb60685528cabb9da2"
application_url = "https://adware-manuals-casa-semester.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://adware-manuals-casa-semester.trycloudflare.com/auth/callback",
  "https://adware-manuals-casa-semester.trycloudflare.com/auth/shopify/callback",
  "https://adware-manuals-casa-semester.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sealion4.myshopify.com"
